version: '3.0'
services:
        backend:
                image: vivekbonde2003/flaskapp:latest
                ports:
                   - "5000:5000"
                environment:
                  MYSQL_HOST: "mysql"
                  MYSQL_USER: "admin"
                  MYSQL_PASSWORD: "admin"
                  MYSQL_DB: "myDb"

                depends_on:
                      - mysql

        mysql:
                image: mysql:5.7
                environment:
                        MYSQL_DATABASE: "myDb"
                        MYSQL_USER: "admin"
                        MYSQL_PASSWORD: "admin"
                        MYSQL_ROOT_PASSWORD: "admin"

                ports:
                   - "3306:3306"

                volumes:
                     - ./message.sql:/docker-entrypoint-initdb.d/message.sql
                     - mysql-data:/var/lib/mysql

volumes:
     mysql-data:
